// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcsevtixfmcikjhnjobf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjc2V2dGl4Zm1jaWtqaG5qb2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODYyNTksImV4cCI6MjA2OTA2MjI1OX0.QT7nm4XriO3ZTcpFT5asMTCd2993gTsu1fMngqhi8ME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});